### ISSUE TITLE
New Commands

### ISSUE THREAD

**Issue by TBNRItzDoge** [xXNiceAssasinl0/EssentialsCore#2]
Possibly a PERMSUI?

**Comment by xXNiceAssasinl0** [comment]
I’ll try

**Comment by xXNiceAssasinl0** [comment]
What I mean by PermsUI

**Comment by TBNRItzDoge** [comment]
you basically select the rank in a ui and u can select what perms to add to
each rank

**Comment by xXNiceAssasinl0** [comment]
That is for PurePerms.
